#!/usr/bin/python

from PyQt4.QtCore import *
from PyQt4.QtGui import *
import sys

class Charged(QDialog) :
	def __init__(self,parent=None) :
		super(Charged,self).__init__(parent)

		self.text = QLabel('<font color=white size=5><b>Battery fully charged. Unplug the charger</b></font>')
		hup_layout = QHBoxLayout()
		hup_layout.addStretch()
		hup_layout.addWidget(self.text)
		hup_layout.addStretch()
		hup_layout.addStretch()

		hlow_layout = QHBoxLayout()
		hlow_layout.addStretch()
		close = QPushButton('&close')
		hlow_layout.addWidget(close)
		close.setStyleSheet('QPushButton{	background-color:blue;'
							'border-style:outset;'
							'border-width:2px;'
							'border-color:white;'
							'border-radius:10px;'
							'font:bold14px;'
							'min-width:8em;'
							'min-height:28px}')

		layout = QGridLayout()
		layout.addLayout(hup_layout,0,0)
		layout.addLayout(hlow_layout,1,0)

		self.setLayout(layout)
		self.connect(close,SIGNAL('clicked()'),app.quit)

		self.resize(1366,120)
		self.move(0,324)
		self.setWindowFlags(Qt.CustomizeWindowHint)
		self.setStyleSheet('background-color:blue')

app = QApplication(sys.argv)
charged = Charged()
charged.show()
app.exec_()
